export const options = [{
  id:"1",
  type:'classic',
  min:0,
  max:20,
  list: [
    {no:420,artist:'Joy Division',album_name:'Unknown Pleasures',year:1979,genre:'Post Punk',length:'40 mins',link:'https://open.spotify.com/album/5Dgqy4bBg09Rdw7CQM545s?si=W8hGMwe-T364gCp0R6B_rw',tracks:10,review:`<p>Unknown Pleasures is the debut studio album by the English rock band Joy Division, released on 15 June 1979, by Factory Records. The album was recorded and mixed over three successive weekends at Stockport's Strawberry Studios in April 1979, with producer Martin Hannett contributing a number of unconventional recording techniques to the group's sound.</p>
      <p>The cover artwork was designed by artist Peter Saville, using a data plot of signals from a radio pulsar. It is the only Joy Division album released during lead singer Ian Curtis's lifetime</p>
      <p>Factory Records did not release any singles from Unknown Pleasures, and the album did not chart despite the relative success of the group's follow-up single, "Transmission". It has since received sustained critical acclaim as an influential post-punk album, and has been named as one of the best albums of all time by publications such as NME, AllMusic, Select, Rolling Stone, and Spin.</p>`}
      ,
    {no:10,artist:'Radiohead',album_name:'Kid A',year:2000,genre:'Art Rock',length:'47 mins',link:'https://open.spotify.com/album/6GjwtEZcfenmOf6l18N7T7?si=R5FEzOZ6QUu4j3zv9jo6MA',tracks:10,review:`<p>Kid A is the fourth studio album by the English rock band Radiohead, released on 2 October 2000 by Parlophone. It was recorded with their producer, Nigel Godrich, in Paris, Copenhagen, Gloucestershire and Oxfordshire.</p>
      <p>Departing from their earlier sound, Radiohead incorporated influences from electronic music, krautrock, jazz and 20th-century classical music, with a wider range of instruments and effects. The singer, Thom Yorke, wrote impersonal and abstract lyrics, cutting up phrases and assembling them at random.</p>
      <p>In a departure from industry practice, Radiohead released no singles and conducted few interviews and photoshoots. Instead, they released short animations and became one of the first major acts to use the internet for promotion.</p>`}
      ,
    {no:984,artist:'Sonic Youth',album_name:'Goo',year:1990,genre:'Noise Rock',length:'49 mins',link:'https://open.spotify.com/album/5iYYQwB0oH9FVyVlaOXZdr?si=K6qrNgF8QrO0e88fZoOD6g',tracks:11,review:`<p>Goo is the sixth full-length studio album by American alternative rock band Sonic Youth, released on June 26, 1990, by DGC Records.</p>
      <p>For this album, the band sought to expand upon its trademark alternating guitar arrangements and the layered sound of their previous album Daydream Nation (1988) with songwriting that was more topical than past works, exploring themes of female empowerment and pop culture.</p>
      <p>Coming off the success of Daydream Nation, Nick Sansano returned to engineer Goo, but veteran producer Ron Saint Germain was chosen by Sonic Youth to finish mixing the album following Sansano's dismissal.</p>`}
      ,
    {no:564,artist:'Slowdive',album_name:'Souvlaki',year:1993,genre:'Shoegaze',length:'40 mins',link:'https://open.spotify.com/album/53eHm1f3sFiSzWMaKOl98Z?si=ygca5aUhTfCZ7GuULwkC-Q',tracks:10,review:`<p>Souvlaki is the second studio album by the English rock band Slowdive. It was recorded in 1992, and released on 1 June 1993 by Creation Records.</p>
      <p>Prior to the writing of Souvlaki, Slowdive co-vocalists and guitarists Rachel Goswell and Neil Halstead had ended their relationship and Halstead began to spend more time writing songs alone, a process that had been completed by the full band in the past</p>
      <p>On its initial release, Souvlaki peaked at number 51 on the UK Albums Chart and was greeted with tepid reviews from critics. It has since received retrospective critical acclaim and has been hailed as a classic of the shoegaze genre.</p>`}
      ,
    {no:154,artist:'MF Doom',album_name:'Mm..Food',year:2004,genre:'Hip Hop',length:'48 mins',link:'https://open.spotify.com/album/1UcS2nqUhxrZjrBZ3tHk2N?si=f53bf64c17ff490c',tracks:15,review:`<p><strong>MM..FOOD</strong> is the fifth studio album by the iconic rapper MF DOOM, released on November 16, 2004. The album is a concept project centered around food-related themes, showcasing DOOM's signature wordplay, intricate rhymes, and unique sampling techniques.</p>
      <p>Tracks like "Beef Rapp," "Rapp Snitch Knishes," and "Potholderz" creatively weave culinary references with sharp social commentary, making the album both humorous and thought-provoking. The production, primarily handled by DOOM himself, is filled with jazz, soul, and old-school hip-hop influences.</p>
      <p>MM..FOOD is often celebrated as one of MF DOOM's best works, solidifying his reputation as one of hip-hop's most innovative and enigmatic figures. The album's quirky and offbeat style has earned it a dedicated following and a place in the pantheon of underground hip-hop classics.</p>`
    },
    {no:124,artist:'Aphex Twin',album_name:'Drukqs',year:2001,genre:'IDM',length:'1hr 40 mins',link:'https://open.spotify.com/album/2oJo7cB45gMVuRsaWNwDq2?si=oE8AhbRlSkOym8f7NHyPdg',tracks:30,review:`<p><strong>Drukqs</strong> is the fifth studio album by the British electronic artist Aphex Twin, released on October 22, 2001. The album is a sprawling double-disc collection that showcases Richard D. James' versatility, ranging from intricate and abrasive breakbeats to serene piano compositions.</p>
      <p><em>Drukqs</em> features some of Aphex Twin's most complex and experimental work, with tracks like "Vordhosbn" and "Mt Saint Michel + Saint Michaels Mount" pushing the boundaries of IDM (Intelligent Dance Music). The album also includes more minimalist pieces like "Avril 14th," a gentle piano melody that has since gained widespread recognition.</p>
      <p>Despite its initially polarizing reception, <em>Drukqs</em> has grown in stature over the years, appreciated for its depth and the way it encapsulates the diverse styles that Aphex Twin is known for. It remains a significant entry in his discography, influencing countless electronic artists who followed.</p>`
    }, 
    {no:504,artist:'Massive Attack',album_name:'Mezzanine',year:1998,genre:'Trip Hop',length:'1hr 3 mins',link:'https://open.spotify.com/album/49MNmJhZQewjt06rpwp6QR?si=163ca19e422944e7',tracks:11,review:`<p><strong>Mezzanine</strong> is the third studio album by British trip-hop group Massive Attack, released on April 20, 1998. The album marked a departure from their previous sound, incorporating darker, more experimental elements and drawing on influences from genres such as post-punk, dub, and electronica.</p>
      <p>Featuring iconic tracks like "Teardrop," "Angel," and "Inertia Creeps," <em>Mezzanine</em> is known for its brooding atmosphere, dense production, and haunting vocals. The album's use of samples, layered textures, and heavy basslines created a sound that was both groundbreaking and influential, setting a new standard for trip-hop and electronic music.</p>
      <p><em>Mezzanine</em> is often regarded as Massive Attack's magnum opus and one of the greatest albums of the 1990s. Its innovative sound continues to resonate with listeners and has left a lasting impact on the music industry.</p>`
    },
    {no:104,artist:'Drive Like Jehu',album_name:'Yank Crime',year:1994,genre:'Post Hardcore',length:'1hr 9 mins',link:'https://open.spotify.com/album/7AHbaRIYnilUwe981nZpmi?si=Vj6h7bZFT1OGBZF5NnJm4w',tracks:12,review:`<p><strong>Yank Crime</strong> is the second and final studio album by American post-hardcore band Drive Like Jehu, released in 1994. The album is celebrated for its intense energy, complex guitar work, and raw, unpolished sound, which helped define the post-hardcore genre.</p>
      <p><em>Yank Crime</em> features tracks like "Here Come the Rome Plows" and "Luau," which showcase the band's aggressive style and intricate musicianship. The album's use of dissonance, unconventional song structures, and dynamic shifts set it apart from other releases of the time.</p>
      <p>Though initially overlooked, <em>Yank Crime</em> has since gained a cult following and is considered a seminal release in the post-hardcore genre. Its influence can be heard in the work of many bands that followed in the punk and alternative scenes.</p>`
    },
    {no:224,artist:'Wilco',album_name:'Yankee Hotel Foxtrot',year:2002,genre:'Contemporary Folk',length:'53 mins',link:'https://open.spotify.com/album/0rPtXOMN42nsLDiShvGamv?si=49db8ce5beea440a',tracks:11,review:`<p><strong>Yankee Hotel Foxtrot</strong> is the fourth studio album by American rock band Wilco, released on April 23, 2002. The album is known for its blend of alternative rock, experimental sounds, and Americana, creating a distinct and innovative sound that has since become iconic.</p>
      <p>Featuring tracks like "I Am Trying to Break Your Heart," "Jesus, Etc.," and "Heavy Metal Drummer," <em>Yankee Hotel Foxtrot</em> explores themes of disillusionment, love, and change. The album's production, which includes elements of noise, electronic effects, and unconventional arrangements, was groundbreaking for its time.</p>
      <p>Despite its challenging creation and initial label rejection, <em>Yankee Hotel Foxtrot</em> was met with critical acclaim and has since been hailed as one of the greatest albums of the 2000s. Its influence on alternative and indie music is profound, and it remains a beloved classic in Wilco's discography.</p>`
    },
    {no:624,artist:'Kate Bush',album_name:'The Kick Inside',year:1978,genre:'Dream Pop',length:'43 mins',link:'https://open.spotify.com/album/5NKTuBLCYhN0OwqFiGdXd1?si=deXyrvEgSjWdjhcXymGP5g',tracks:13,review:`<p><strong>The Kick Inside</strong> is the debut studio album by British singer-songwriter Kate Bush, released on February 17, 1978. The album, which was written by Bush when she was just a teenager, showcases her unique voice, poetic lyrics, and eclectic blend of rock, art pop, and folk influences.</p>
      <p>The album features the iconic single "Wuthering Heights," which topped the UK charts and introduced the world to Bush's distinctive style. Other tracks like "The Man with the Child in His Eyes" and "Feel It" highlight her emotional depth and innovative songwriting.</p>
      <p><em>The Kick Inside</em> was a critical and commercial success, establishing Kate Bush as one of the most original and influential artists of her time. The album's blend of mysticism, romance, and literary references set the stage for her illustrious career and has left a lasting legacy in the world of music.</p>`
    },
    {no:964,artist:'Natural Snow Buildings',album_name:'Daughters of Darkness',year:2013,genre:'Dark Ambient',length:'7hr 20 mins',link:'https://open.spotify.com/album/6FNu7RUEKOGhdgZenZKg4s?si=485ea756c11a4373',tracks:18,review:`<p><strong>Daughters of Darkness</strong> is a limited-edition album by the French experimental duo Natural Snow Buildings, released in 2009. The album is inspired by the 1971 horror film of the same name, and it showcases the band's signature blend of drone, folk, and ambient music, creating a haunting and immersive soundscape.</p>
      <p>Featuring lengthy, atmospheric tracks like "Her Face Among the Shadows" and "The Rising Portal," <em>Daughters of Darkness</em> is characterized by its use of dense, layered textures, ethereal melodies, and a sense of cinematic storytelling. The album's minimalist approach, combined with its eerie and mystical atmosphere, makes it a unique and captivating listening experience.</p>
      <p>Though released in a very limited quantity, <em>Daughters of Darkness</em> has become a sought-after release among fans of experimental and drone music. The album is often praised for its ability to evoke a sense of otherworldliness and its deep, meditative qualities, solidifying Natural Snow Buildings' reputation as one of the most intriguing acts in the underground music scene.</p>`
    },
    {no:774,artist:'Sigur Ros',album_name:'Ágætis Byrjun',year:1999,genre:'Post Rock',length:'1hr 11 mins',link:'https://open.spotify.com/album/1DMMv1Kmoli3Y9fVEZDUVC?si=94TKYi-4TpiVF5fam3CsHA',tracks:10,review:`<p><strong>Ágætis Byrjun</strong> is the second studio album by Icelandic post-rock band Sigur Rós, released on June 12, 1999. The album marked the band's breakthrough, introducing their ethereal and expansive sound to a global audience. It's often considered one of the most influential post-rock albums of all time.</p>
      <p><em>Ágætis Byrjun</em> features iconic tracks like "Svefn-g-englar" and "Starálfur," characterized by Jónsi's distinctive falsetto vocals, bowed guitar, and lush, orchestral arrangements. The album's dreamy and otherworldly atmosphere, combined with its emotional depth, has captivated listeners and critics alike.</p>
      <p>The album's title translates to "A Good Beginning," and it indeed signaled the start of Sigur Rós's rise to international acclaim. <em>Ágætis Byrjun</em> has been lauded for its beauty and innovation, solidifying Sigur Rós's place as one of the most important bands in the post-rock genre.</p>`
    },
    {no:714,artist:'Unwound',album_name:'The Future of What',year:1995,genre:'Post Hardcore',length:'1hr',link:'https://open.spotify.com/album/58JOh530ehOoClp4RLYwiH?si=6aa5a52ffde74f5b',tracks:17,review:`<p><strong>The Future of What</strong> is the third studio album by American post-hardcore band Unwound, released on April 24, 1995. The album is known for its raw energy, dissonant guitar work, and aggressive yet experimental approach to the post-hardcore genre.</p>
      <p>Tracks like "New Energy" and "Demons Sing Love Songs" showcase the band's ability to blend noise, punk, and art rock influences into a cohesive and powerful sound. The album's abrasive textures and complex rhythms set it apart from other releases of the time, making it a significant work in the 90s underground music scene.</p>
      <p><em>The Future of What</em> is often regarded as one of Unwound's most essential albums, capturing the band's intensity and willingness to push the boundaries of their genre. It remains a touchstone for fans of post-hardcore and experimental rock.</p>`
    },
    {no:54,artist:'Duster',album_name:'Stratosphere',year:1998,genre:'Slowcore',length:'53 mins',tracks:17,link:'https://open.spotify.com/album/2S3289mypNw2zP0OpFexMb?si=c058d7664f924791',review:`<p><strong>Stratosphere</strong> is the debut studio album by American slowcore band Duster, released on February 24, 1998. The album is a key release in the slowcore and space rock genres, known for its lo-fi production, melancholic atmosphere, and minimalist instrumentation.</p>
      <p>Tracks like "Gold Dust" and "Echo, Bravo" feature the band's signature sound: sparse arrangements, reverb-drenched guitars, and distant vocals. The album's introspective mood and subtle dynamics have earned it a dedicated cult following over the years.</p>
      <p><em>Stratosphere</em> is often praised for its emotional depth and the way it captures a sense of isolation and quiet beauty. It has become a seminal album in the slowcore genre and continues to influence artists who appreciate its understated yet powerful impact.</p>`
    },
    {no:331,artist:'Björk',album_name:'Post',year:1995,genre:'Art Pop',length:'56 mins',tracks:11,link:'https://open.spotify.com/album/2lYwBB5l7GqgyHFTHz0Itd?si=b7d98b5232444078',review:`<p><strong>Post</strong> is the second studio album by Icelandic artist Björk, released on June 13, 1995. The album is a diverse and adventurous mix of electronic, pop, trip-hop, and orchestral music, showcasing Björk's eclectic influences and her innovative approach to songwriting and production.</p>
      <p>Featuring hits like "Army of Me," "Hyperballad," and "It's Oh So Quiet," <em>Post</em> explores themes of love, independence, and emotional resilience. The album's bold experimentation with different genres and its dynamic arrangements have made it one of Björk's most celebrated works.</p>
      <p><em>Post</em> solidified Björk's reputation as a groundbreaking artist in the 90s and has been praised for its creativity, emotional depth, and fearless exploration of new sounds. It remains a defining album in her career and a landmark in contemporary music.</p>`
    },
    {no:775,artist:'my bloody valentine',album_name:'loveless',year:1991,genre:'Shoegaze',length:'48 mins',tracks:11,link:'https://open.spotify.com/album/3USQKOw0se5pBNEndu82Rb?si=5750d5842ff04be1',review:`<p>"Loveless" is the second studio album by the Irish-English rock band My Bloody Valentine, released in November 1991. The album is widely regarded as a landmark in the shoegaze genre, known for its dense, immersive soundscapes and innovative production techniques. "Loveless" is characterized by its use of heavily layered guitars, often described as a "wall of sound," combined with ethereal vocals and intricate melodies. The album's unique sound was achieved through extensive use of effects pedals, pitch bending, and studio experimentation, creating a dreamy, almost otherworldly atmosphere. Tracks like "Only Shallow" and "When You Sleep" are emblematic of the album's rich textures and hypnotic rhythms.</p>
      <p>The creation of "Loveless" was infamously protracted and costly, with the recording process spanning nearly two years and involving multiple studios. Despite the challenges, the band, led by Kevin Shields, succeeded in crafting an album that pushed the boundaries of what rock music could sound like. The album's lyrics are often obscured in the mix, adding to its enigmatic and haunting quality. While the vocals are understated, they complement the swirling guitar work and contribute to the overall sense of disorientation and beauty that defines the album. The production, which layers sound upon sound, results in a listening experience that is both overwhelming and deeply emotive.</p>
      <p>Upon its release, "Loveless" received critical acclaim and has since been hailed as one of the greatest albums of the 1990s. It has had a lasting influence on a wide range of genres, including indie rock, alternative, and electronic music. The album's innovative approach to sound and texture has inspired countless artists and continues to be revered by fans and critics alike. "Loveless" remains a seminal work in My Bloody Valentine's discography, and its impact on music is still felt today, making it a timeless classic in the world of alternative music.</p>`
    },
    {no:443,artist:'Pink Floyd',album_name:'The Dark Side of the Moon',year:1973,tracks:10,genre:'Progressive Rock',length:'42 mins',link:'https://open.spotify.com/album/4LH4d3cOWNNsVw41Gqt2kv?si=jpXNGDhcSCu4aVKPVwjD1w',review:`<p><strong>The Dark Side of the Moon</strong> is the eighth studio album by the English rock band Pink Floyd, released in March 1973. The album is one of the most critically acclaimed and commercially successful albums of all time, known for its complex compositions, philosophical lyrics, and groundbreaking production. <strong>The Dark Side of the Moon</strong> explores themes such as conflict, greed, time, death, and mental illness, reflecting the pressures of modern life. The album's seamless flow from one track to the next, along with its innovative use of studio effects, has made it a defining work of progressive rock. Iconic tracks like "Time," "Money," and "Us and Them" are central to its enduring legacy.</p>
      <p>The album was recorded at Abbey Road Studios in London and was produced by the band members along with engineer Alan Parsons. The use of multitrack recording, synthesizers, and tape loops contributed to the album's distinctive sound, which was both experimental and accessible. <strong>The Dark Side of the Moon</strong> also features the contributions of session musicians, including female vocalists who provided the memorable backing vocals on tracks like "The Great Gig in the Sky." The album's cover, designed by Storm Thorgerson and Hipgnosis, features the iconic prism and rainbow, symbolizing the band's exploration of light and sound.</p>
      <p>Upon its release, <strong>The Dark Side of the Moon</strong> received universal acclaim and became one of the best-selling albums of all time, remaining on the Billboard charts for over 900 weeks. Its influence on music, culture, and even science is immense, and it continues to be a touchstone for musicians and listeners alike. The album's exploration of universal human experiences, coupled with its innovative production techniques, has ensured its place as a timeless classic. <strong>The Dark Side of the Moon</strong> remains a pinnacle of Pink Floyd's career and a milestone in the history of rock music.</p>`
    },
    {
      no:87,artist:'Portishead',album_name:'Dummy',year:1994,tracks:11,length:'49 mins',genre:'Trip Hop',link:'https://open.spotify.com/album/3539EbNgIdEDGBKkUf4wno?si=-7RY3KzURyqi6l790CqVOA',review:`<p><strong>Dummy</strong> is the debut studio album by the English electronic music group Portishead, released in August 1994. The album is a seminal work in the trip-hop genre, known for its moody, atmospheric sound and innovative production. <strong>Dummy</strong> is characterized by its use of haunting vocals, sample-based instrumentation, and a blend of hip-hop, jazz, and soul influences. Tracks like &quot;Sour Times&quot; and &quot;Glory Box&quot; showcase the album&apos;s distinctive sound, featuring eerie, downtempo beats and melancholic melodies.</p>
      <p>The production of <strong>Dummy</strong> is marked by its use of vintage samples, unconventional recording techniques, and a focus on creating a dark, immersive atmosphere. The album&apos;s instrumentation often includes lush strings, dusty drum breaks, and layered vocal effects, all contributing to its cinematic quality. Beth Gibbons&apos; emotive vocal performances add a sense of emotional depth and introspection, enhancing the album&apos;s overall impact. The album&apos;s innovative use of samples and its unique production approach have been influential in shaping the sound of 90s electronic music.</p>
      <p>Upon its release, <strong>Dummy</strong> received widespread critical acclaim and has since been regarded as a classic of the trip-hop genre. Its impact on music and culture has been significant, influencing a wide range of artists and genres. The album&apos;s blend of genre-defying elements and its ability to evoke a strong emotional response continue to resonate with listeners, making <strong>Dummy</strong> a timeless and influential work in the realm of electronic music.</p>`
    },
    {
      no:136,artist:'PJ Harvey',album_name:'Rid of Me',year:1993,tracks:14,length:'49 mins',genre:'Alternative Rock',link:'https://open.spotify.com/album/2fDJpBJhtloxzUENHlU9JB?si=M9mKocz1QueJt6x-rkCQVw',review:`<p><strong>Rid of Me</strong> is the second studio album by English singer-songwriter PJ Harvey, released in April 1993. The album is known for its raw, intense sound and its exploration of themes such as love, anger, and desire. <strong>Rid of Me</strong> features a blend of grunge, alternative rock, and punk influences, characterized by its powerful guitar riffs, aggressive drumming, and PJ Harvey&apos;s emotive vocal delivery. Tracks like &quot;Rid of Me&quot; and &quot;50ft Queenie&quot; highlight the album&apos;s dynamic range, showcasing both its ferocity and its moments of vulnerability.</p>
      <p>The production of <strong>Rid of Me</strong> was handled by Steve Albini, known for his minimalist and direct approach. The album&apos;s sound is characterized by its stripped-down, raw quality, with Albini&apos;s production emphasizing the stark, visceral nature of Harvey&apos;s music. The use of heavy, distorted guitars and stark, powerful drumming creates a sense of urgency and intensity throughout the album. PJ Harvey&apos;s lyrics are often confrontational and poetic, adding depth and complexity to the album&apos;s themes.</p>
      <p>Upon its release, <strong>Rid of Me</strong> received critical acclaim for its originality and emotional depth. The album is considered a landmark in PJ Harvey&apos;s career, establishing her as a major force in alternative rock. Its influence can be seen in the work of numerous artists who have been inspired by Harvey&apos;s bold approach to songwriting and production. <strong>Rid of Me</strong> remains a powerful and enduring work, celebrated for its uncompromising sound and its exploration of raw, personal themes.</p>`
    },
    {
      no:687,artist:'',album_name:'Power Corruption and Lies',year:1983,tracks:8,length:'42 mins',genre:'New Wave',link:'https://open.spotify.com/album/6NTrwu1XJ56jBPx7HMksbZ?si=boPo-YOXT9-qc_jrQMvAew',review:`<p><strong>Power, Corruption & Lies</strong> is the second studio album by the English rock band New Order, released in May 1983. The album marks a significant evolution in the band&apos;s sound, embracing a more electronic and synth-driven approach compared to their debut. <strong>Power, Corruption & Lies</strong> is characterized by its innovative use of synthesizers, driving basslines, and a blend of post-punk and dance music influences. Tracks like &quot;Blue Monday&quot; and &quot;Age of Consent&quot; exemplify the album&apos;s pioneering use of electronic elements and its influence on the development of synth-pop and dance music.</p>
      <p>The production of <strong>Power, Corruption & Lies</strong> was handled by the band themselves, with a focus on creating a polished yet dynamic sound. The album features a distinctive blend of melodic synth lines, rhythmic drum patterns, and Bernard Sumner&apos;s distinctive vocals. The use of the iconic synth bass on tracks like &quot;The Village&quot; and &quot;5-8-6&quot; adds to the album&apos;s infectious and danceable quality. The lyrical content often explores themes of personal and political struggle, delivered through a combination of catchy melodies and introspective lyrics.</p>
      <p>Upon its release, <strong>Power, Corruption & Lies</strong> was met with widespread critical acclaim and has since been regarded as a seminal album in the synth-pop and electronic music genres. Its innovative approach to production and its influence on subsequent music have solidified its place as a classic. The album&apos;s ability to blend electronic experimentation with accessible pop sensibilities continues to resonate with listeners, making <strong>Power, Corruption & Lies</strong> a landmark work in New Order&apos;s discography and in the broader context of 1980s music.</p>`
    }                                                                                                                                                                                                               
  ]
},{id:"2",
  type:'creator',
  min:0,
  max:16,
  list:[
    {no:120,artist:'Weyes Blood',album_name:'Titanic Rising',year:2019,genre:'Chamber Pop',length:'42 mins',tracks:10,link:'https://open.spotify.com/album/0Cuqhgy8vm96JEkBY3polk?si=3f6cc33121914ebc',review:`<p>Titanic Rising is the fourth studio album by American singer-songwriter and musician Weyes Blood, released on April 5, 2019 by Sub Pop.</p><p>Produced by the artist along with Jonathan Rado, it is influenced by 1970s FM radio. Its lyrical themes address romantic pursuits, climate change, and references to the Titanic.</p>
  <p>The album is named after the RMS Titanic and the 1997 film based on the ship's sinking, which had a profound impact on Mering when she was younger.</p>`}
    ,{no:890,artist:'Black Country, New Road',album_name:'Ants From Up There',year:2022,genre:'Chamber Pop',length:'58 mins',tracks:10,link:'https://open.spotify.com/album/21xp7NdU1ajmO1CX0w2Egd?si=4291e667174b46b4',review:`<p><strong>Ants From Up There</strong> is the second studio album by the British band Black Country, New Road (BCNR), released on February 4, 2022. The album received widespread critical acclaim for its unique blend of post-rock, chamber pop, and experimental rock elements, marking a significant evolution from their debut album.</p>
  <p>The album explores themes of love, loss, and emotional turbulence, with poetic and evocative lyrics. Frontman Isaac Wood's intense and heartfelt vocals, combined with the band's intricate instrumentation, create a deeply immersive listening experience.</p>
  <p>Notably, <em>Ants From Up There</em> was the last album to feature Isaac Wood as the lead vocalist before his departure from the band. The album's success has cemented BCNR as one of the most innovative and exciting bands in the contemporary music scene.</p>
        `},
        {no:752,artist:'Beach House',album_name:'7',year:2018,genre:'Dream Pop',length:'47 mins',tracks:11,link:'https://open.spotify.com/album/1zN85Ep8w2JORfCe0RHLDP?si=64980e6b5fc1458f',review:`<p><strong>7</strong> is the seventh studio album by the American dream pop duo Beach House, released on May 11, 2018. The album was met with critical acclaim, praised for its lush soundscapes, rich textures, and the duo's ability to evolve their signature dreamy style while exploring new sonic territories.</p>
  <p>With songs like "Dark Spring," "Dive," and "Lemon Glow," <em>7</em> showcases Beach House's exploration of darker themes and more experimental production techniques. The album was co-produced by Sonic Boom (Peter Kember), who brought a fresh perspective to their sound, blending swirling synths, reverb-heavy guitars, and ethereal vocals into a cohesive and mesmerizing experience.</p>
  <p><em>7</em> is considered one of Beach House's most ambitious and mature works, solidifying their status as one of the leading acts in the dream pop genre. The album's intricate layers and emotional depth continue to captivate listeners, making it a standout release in their discography.</p>
        `},
        {no:120,artist:'Deafheaven',album_name:'Sunbather',year:2013,genre:'Blackgaze',length:'59 mins',link:'https://open.spotify.com/album/2kKXGWaCEl06EKZ4DxBJIT?si=5bc447a9486a4743',tracks:7,review:`<p><strong>Sunbather</strong> is the second studio album by American blackgaze band Deafheaven, released on June 11, 2013. The album is a groundbreaking fusion of black metal, shoegaze, and post-rock, creating an intense and emotionally charged sound that has captivated audiences across various genres.</p>
  <p>Thematically, <em>Sunbather</em> explores feelings of longing, existential despair, and fleeting moments of beauty, all conveyed through George Clarke's harrowing vocals and the band's dynamic instrumentation. The album features epic tracks like "Dream House" and "Vertigo," which showcase the band's ability to blend ferocity with melody.</p>
  <p>Widely regarded as a modern classic, <em>Sunbather</em> received critical acclaim for its innovative approach and has since become a seminal album in both the black metal and shoegaze genres. Its striking cover, featuring a vibrant pink gradient, has also become iconic in its own right.</p>
        `},
        {no:114,artist:'Grouper',album_name:'Alien Observer',year:2011,genre:'Ambient',length:'40 mins',tracks:6,link:'https://open.spotify.com/album/4Z1BFX1oBckY8bhGEWMYmi?si=sYbHQjOoRNikJ8sfTvi4og',review:`<p><strong>Alien Observer</strong> is one of two albums released in 2011 as part of Grouper's double album project A I A. Created by musician Liz Harris, Grouper's sound on this album is characterized by ethereal, ambient compositions that evoke a sense of isolation and introspection.</p>
  <p>The album features haunting tracks like "Moon is Sharp" and "Alien Observer," which blend Harris's whispery vocals with minimalistic instrumentation and atmospheric drones. The music on <em>Alien Observer</em> is both intimate and otherworldly, creating a deeply immersive listening experience.</p>
  <p><em>Alien Observer</em> has been praised for its emotional depth and has solidified Grouper's reputation as a key figure in the ambient and experimental music scenes. The album continues to resonate with listeners who appreciate its haunting beauty and meditative qualities.</p>
        `},
        {no:712,artist:'Destroyer',album_name:'Kaputt',year:2011,genre:'Art Pop',length:'50 mins',tracks:9,link:'https://open.spotify.com/album/3yy32elu0ZXO6xq2bTuhmU?si=c7ec93f39cd840d0',review:`<p><strong>Kaputt</strong> is the ninth studio album by Canadian indie rock band Destroyer, released on January 25, 2011. The album marked a stylistic shift for the band, embracing lush, 80s-inspired soft rock and jazz influences, with a focus on smooth production and atmospheric arrangements.</p>
  <p>Tracks like "Chinatown" and "Kaputt" feature saxophones, synthesizers, and Dan Bejar's distinctively cryptic lyrics, creating a dreamy, nostalgic sound that has been widely praised. The album's polished yet melancholic tone offers a reflective look at modern life and the complexities of love and loss.</p>
  <p><em>Kaputt</em> received widespread critical acclaim upon its release and is considered one of Destroyer's most accomplished works. Its unique blend of genres and thoughtful composition has made it a standout album in the indie music landscape.</p>
        `},
        {no:134,artist:'King Gizzard and The Lizard Wizard',album_name:`I'm in Your Mind Fuzz`,year:2014,genre:'Psychedelic Rock',length:'42 mins',tracks:10,link:'https://open.spotify.com/album/1rb4cp4F59Tk1UOPHuP3H0?si=9135d739e737407b',review:`<p><strong>I'm in Your Mind Fuzz</strong> is the fifth studio album by Australian psychedelic rock band King Gizzard & the Lizard Wizard, released on October 31, 2014. The album is known for its fast-paced, mind-bending sound, featuring a continuous, flowing sequence of songs that blend elements of garage rock, psych, and krautrock.</p>
  <p>The album kicks off with a four-track suite—"I'm in Your Mind," "I'm Not in Your Mind," "Cellophane," and "I'm in Your Mind Fuzz"—that seamlessly transitions between songs, creating a hypnotic, driving rhythm. The band's use of microtonal tuning, frenetic guitar riffs, and repetitive grooves makes this album a fan favorite and a key release in their expansive discography.</p>
  <p><em>I'm in Your Mind Fuzz</em> is often celebrated for its high energy and relentless pace, encapsulating the band's unique approach to psychedelic rock. It has become a standout album in their catalog, beloved by fans for its immersive and electrifying experience.</p>
        `},
        {no:654,artist:'The Sound',album_name:'Jeopardy',year:'1980',genre:'Post Punk',length:'39 mins',tracks:11,link:'https://open.spotify.com/album/6QSnitPoyu8x79z1VxtrmV?si=0c29f1c14a634674',review:`<p>Jeopardy is the debut studio album by the English post-punk band The Sound, released in November 1980. The album emerged during a period when the post-punk genre was thriving, and it quickly established The Sound as a significant band within the scene. Produced by Adrian Borland and Nick Robbins, Jeopardy is characterized by its raw, energetic sound, blending dark, introspective lyrics with driving rhythms and jangly guitars. The album's mood is both tense and atmospheric, reflecting the anxieties of the time while also showcasing Borland's distinctive vocal delivery and the band's tight musicianship.</p>
  <p>The album features standout tracks such as "I Can't Escape Myself," "Heartland," and "Missiles," each of which exemplifies The Sound's ability to craft songs that are both emotionally resonant and musically compelling. The lyrics often explore themes of alienation, inner turmoil, and societal disillusionment, which resonated deeply with the post-punk audience. Despite its critical acclaim, Jeopardy did not achieve significant commercial success upon its release, but it has since gained a cult following and is regarded as one of the defining albums of the post-punk era.</p>
  <p>Jeopardy is often praised for its intensity and authenticity, with many considering it a hidden gem within the post-punk genre. The album's minimalist production, combined with its emotionally charged content, has ensured its lasting influence and enduring appeal. Over the years, Jeopardy has been reissued and continues to be celebrated by fans of post-punk and alternative music, solidifying The Sound's place in music history despite their relatively short-lived career.</p>`
        },
        {no:168,artist:'Bark Psychosis',album_name:'Hex',year:1994,genre:'Post Rock',length:'53 mins',tracks:7,link:'https://open.spotify.com/album/7j98uMKCZuBQU1SPcrQAxP?si=a9152dde1a1d4523',review:`<p>"Hex" is the debut studio album by the English band Bark Psychosis, released in 1994. The album is widely regarded as a pioneering work in the genre that would later be known as post-rock. Bark Psychosis, led by Graham Sutton, crafted an album that blends elements of ambient, jazz, and rock, creating a sound that is atmospheric, textured, and introspective. The music on "Hex" is characterized by its use of space, subtle dynamics, and an emphasis on mood over traditional song structures. Tracks like "The Loom" and "A Street Scene" exemplify the band's ability to create immersive soundscapes that draw the listener into their unique sonic world.</p>
  <p>"Hex" was recorded in various locations, including a disused church, which contributed to the album's rich, reverberant sound. The production is meticulous, with each instrument and sound carefully placed to build the album's distinctive atmosphere. The album's compositions often unfold slowly, with an emphasis on creating tension and release through the use of minimalism and repetition. Lyrically, the album touches on themes of urban decay, existential angst, and emotional introspection, reflecting the bleak yet beautiful tone of the music.</p>
  <p>Despite its critical acclaim, "Hex" did not achieve major commercial success, but it has since become a cult classic and is considered a landmark release in the evolution of post-rock. The album's influence can be heard in the work of later bands in the genre, and it remains a touchstone for fans and musicians alike. "Hex" is celebrated for its innovation and its ability to create a deeply emotional and atmospheric listening experience, solidifying Bark Psychosis as one of the most important and influential bands in the post-rock movement.</p>`
        },
        {no:871,artist:'Godspeed You! Black Emperor',album_name:'F♯ A♯ ∞',year:'1998',genre:'Post Rock',length:'1hrs',tracks:3,link:'https://open.spotify.com/album/7sh2Z8jj1iySpHRAnGd9w5?si=17c372d1b2ea4287',review:`<p>"F♯ A♯ ∞" is the debut studio album by the Canadian post-rock band Godspeed You! Black Emperor, released in 1997. The album is notable for its expansive, cinematic sound, blending elements of orchestral music, drone, and ambient with rock instrumentation. "F♯ A♯ ∞" is divided into two long tracks, each split into multiple movements, creating a continuous, evolving narrative through sound. The album's haunting atmosphere is built through the use of field recordings, tape loops, and a wide array of instruments, including strings, guitars, and percussion. The music is both dark and beautiful, often evoking a sense of apocalyptic foreboding.</p>
  <p>The album's title, "F♯ A♯ ∞", reflects its thematic ambiguity and its sense of infinite, unresolved tension. The tracks, "The Dead Flag Blues" and "East Hastings," are known for their slow builds, crescendos, and stark contrasts between moments of quiet introspection and intense, powerful climaxes. The band's use of unconventional structures and extended compositions set them apart from other bands at the time and established their reputation as pioneers of the post-rock genre. The album's production is raw and organic, contributing to its visceral impact and emotional depth.</p>
  <p>Since its release, "F♯ A♯ ∞" has been critically acclaimed and is considered a seminal work in the post-rock genre. The album's influence can be seen in the work of many bands that followed, and it remains a touchstone for its innovative approach to composition and sound design. Godspeed You! Black Emperor's ability to create a deeply immersive and emotionally charged listening experience with "F♯ A♯ ∞" has solidified the album's place as a landmark release in experimental music, continuing to captivate listeners with its timeless and otherworldly sound.</p>`
        },
        {no:591,artist:'Julia Holter',album_name:'Have You In My Wilderness',year:2015,genre:'Dream Pop',length:'47 mins',tracks:10,link:'https://open.spotify.com/album/0EiGGBzF9wzJn2X8F0Yvjh?si=1805e48db5894351',review:`<p>"Have You in My Wilderness" is the fourth studio album by American singer-songwriter and multi-instrumentalist Julia Holter, released in September 2015. The album marks a significant evolution in Holter's sound, blending her experimental roots with more accessible, pop-oriented elements. "Have You in My Wilderness" is characterized by its lush orchestration, intricate arrangements, and Holter's ethereal vocals. The songs on the album explore themes of love, desire, and human connection, all while maintaining a sense of mystery and introspection. Tracks like "Feel You" and "Sea Calls Me Home" exemplify the album's delicate balance between complexity and emotional directness.</p>
  <p>The album's production is richly textured, with a focus on layering strings, keyboards, and subtle electronic elements to create an immersive soundscape. Holter's songwriting on "Have You in My Wilderness" is both sophisticated and deeply personal, drawing on influences from classical music, jazz, and art-pop. The album's lyrics often weave poetic imagery with narrative fragments, inviting listeners into a world that is both intimate and elusive. The combination of Holter's expressive voice and the album's meticulous production results in a listening experience that is both captivating and haunting.</p>
  <p>"Have You in My Wilderness" received widespread critical acclaim upon its release, with many praising its blend of experimental ambition and melodic beauty. The album was celebrated for its artistic depth and emotional resonance, solidifying Julia Holter's reputation as one of the most innovative and compelling artists in contemporary music. As a work that bridges the gap between the avant-garde and the accessible, "Have You in My Wilderness" remains a standout in Holter's discography and a beloved album among fans of art-pop and experimental music.</p>`
        },
        {
          no:122,artist:'Have A Nice Life',album_name:'Deathconsciousness',year:2008,genre:'Industrial Rock',length:'1hr 24mins',tracks:13,link:'https://open.spotify.com/album/6MH3CAXp8AN8ELrbex18dM?si=9rHPjgJ4SNeEBWEL92bTaw',review:`<p><strong>Deathconsciousness</strong> is the debut studio album by the American experimental rock band Have a Nice Life, released in 2008. The album has garnered a cult following for its unique blend of post-punk, shoegaze, industrial, and ambient influences, creating a dark, immersive listening experience. The album was recorded over five years in various locations, reflecting its lo-fi production and deeply personal themes. <strong>Deathconsciousness</strong> is divided into two parts, "The Plow That Broke the Plains" and "The Future," each exploring themes of existential despair, nihilism, and the search for meaning in a seemingly indifferent universe. The album's bleak tone is complemented by its haunting melodies and dense soundscapes.</p>
  <p>The album's production is intentionally raw, with a heavy emphasis on reverb and distortion, contributing to its overwhelming and suffocating atmosphere. Tracks like "Bloodhail" and "Earthmover" are characterized by their slow builds and cathartic releases, with lyrics that delve into themes of death, loss, and existential dread. The use of layered guitars, droning synths, and pounding drums creates a wall of sound that envelops the listener, while the distant, echoing vocals add to the sense of isolation and melancholy. <strong>Deathconsciousness</strong> also includes an extensive booklet that provides additional context and insight into the album's themes, drawing on historical and philosophical references to enhance the narrative.</p>
  <p>Despite its initially limited release, <strong>Deathconsciousness</strong> has been widely praised by critics and fans alike, with many considering it a landmark album in the underground music scene. Its impact has grown over time, influencing a wide range of genres, including black metal, post-rock, and gothic rock. The album's introspective and often harrowing content, combined with its innovative approach to sound and structure, has cemented <strong>Deathconsciousness</strong> as a seminal work in modern experimental music. Its enduring popularity continues to resonate with listeners who connect with its exploration of the darker aspects of the human experience.</p>`     
        },
        {
          no:994,artist:'Boards of Canada',album_name:'Geogaddi',year:2002,genre:'IDM',length:'59 mins',tracks:21,link:'https://open.spotify.com/album/4T7JGfRryhw5POaXalkApE?si=eugYXIW-TquTpfrpzxa2rQ',review:`<p><strong>Geogaddi</strong> is the second studio album by the Scottish electronic music duo Boards of Canada, released in February 2002. Known for its distinctive blend of ambient, downtempo, and IDM (Intelligent Dance Music), the album continues the duo&apos;s exploration of nostalgic and enigmatic soundscapes. <strong>Geogaddi</strong> is characterized by its use of lush, atmospheric textures, analog synthesizers, and heavily processed samples, creating a rich, immersive experience. The album&apos;s sound is often described as haunting and surreal, with a sense of both warmth and unease. Tracks like &quot;Music Is Math&quot; and &quot;Gyroscope&quot; exemplify the album&apos;s intricate production and its ability to evoke a sense of mystery and introspection.</p>
  <p>The album&apos;s concept revolves around themes of memory, childhood, and the passage of time, and it is known for its cryptic and sometimes unsettling samples. <strong>Geogaddi</strong> features a complex and layered sound design, with many tracks incorporating subtle, distorted vocal samples and field recordings that contribute to its dreamlike quality. The duo&apos;s use of vintage equipment and unconventional recording techniques adds to the album&apos;s nostalgic and otherworldly feel. The album&apos;s structure is nonlinear, with tracks blending into each other and creating a continuous, evolving sonic journey.</p>
  <p>Upon its release, <strong>Geogaddi</strong> was met with critical acclaim and has since been regarded as one of Boards of Canada&apos;s most significant works. Its influence can be seen in the wider electronic and ambient music genres, and it continues to be celebrated for its innovative approach to sound and its evocative, atmospheric qualities. The album&apos;s ability to create a deeply immersive and contemplative listening experience has solidified its place as a classic in the realm of electronic music.</p>`
        },
        {
          no:10,artist:'Alvvays',album_name:'Antisocialites',year:2017,tracks:10,length:'32 mins',genre:'Dream Pop',link:'https://open.spotify.com/album/2Yy84EeclNVwFDem6yIB2s?si=qN-53MLbR4y5KHVuutWgJw',review:`<p><strong>Antisocialites</strong> is the second studio album by the Canadian indie pop band Alvvays, released in September 2017. Building on the success of their debut album, <strong>Antisocialites</strong> continues the band&apos;s exploration of melodic pop with a nostalgic, 80s-inspired sound. The album is characterized by its catchy hooks, lush arrangements, and the distinctive vocals of lead singer Molly Rankin. Tracks like &quot;In Undertow&quot; and &quot;Dreams Tonite&quot; showcase the band&apos;s ability to blend upbeat melodies with introspective lyrics, creating a sound that is both engaging and emotionally resonant.</p>
  <p>The production of <strong>Antisocialites</strong> features a polished, yet warm sound, with a mix of jangly guitars, synths, and driving rhythms that enhance the album&apos;s retro vibe. The lyrics explore themes of love, heartache, and self-reflection, often framed within the context of personal relationships and the challenges of modern life. The album&apos;s cohesive sound and thoughtful songwriting have been praised for their depth and charm, with many critics noting its ability to balance pop sensibilities with lyrical complexity.</p>
  <p>Upon its release, <strong>Antisocialites</strong> received critical acclaim and was highlighted as one of the standout indie pop albums of 2017. The album&apos;s successful blend of catchy melodies and introspective themes helped solidify Alvvays&apos; reputation as a key player in the indie pop genre. Its lasting appeal is a testament to the band&apos;s skillful songwriting and their ability to create music that resonates with listeners on both an emotional and nostalgic level.</p>`
        },
        {
          no:31,artist:'black midi',album_name:'Cavalcade',year:2021,tracks:8,length:'42 mins',genre:'Prog Rock',link:'https://open.spotify.com/album/7AsC27VDa3yOksZrfBSD6D?si=JNd3-YrKSd-ehm9sDFvBBA',review:`<p><strong>Cavalcade</strong> is the second studio album by the British experimental rock band Black Midi, released in May 2021. The album continues the band&apos;s exploration of complex and genre-defying music, building on the experimental and eclectic sound established on their debut album. <strong>Cavalcade</strong> is characterized by its ambitious compositions, which blend elements of post-punk, math rock, jazz, and avant-garde. Tracks like &quot>John L&quot; and &quot;Slow&quot; showcase the band&apos;s skillful musicianship and their ability to create intricate, dynamic soundscapes that challenge conventional song structures.</p>
  <p>The production of <strong>Cavalcade</strong> is marked by its innovative arrangements and the band&apos;s use of unconventional instrumentation. The album features a wide range of sonic textures, from frenetic guitar riffs and complex drumming to lush orchestral elements and haunting vocal performances. The lyrics often delve into abstract and surreal themes, contributing to the album&apos;s enigmatic and immersive atmosphere. The band&apos;s creative approach to songwriting and production has been praised for pushing the boundaries of contemporary rock music.</p>
  <p>Upon its release, <strong>Cavalcade</strong> received widespread critical acclaim for its originality and complexity. The album was noted for its ambitious scope and the band&apos;s willingness to experiment with different musical styles and influences. <strong>Cavalcade</strong> has been celebrated as a significant achievement in the experimental rock genre, further establishing Black Midi as one of the most innovative and exciting bands in contemporary music. Its blend of genre-defying elements and intricate compositions continues to captivate and challenge listeners.</p>`
        },
        {
          no:87,artist:'Parquet Courts',album_name:'Wide Awake!',year:2018,tracks:13,length:'38 mins',genre:'Indie Rock',link:'https://open.spotify.com/album/6NTaxSEZsDR5RlGyBzKNmZ?si=6QO44bZsRSaKvUfvNAzWJw',review:`<p><strong>Wide Awake</strong> is the fourth studio album by the American indie rock band Parquet Courts, released in April 2018. The album continues the band&apos;s exploration of witty, socially conscious lyrics and eclectic musical styles. <strong>Wide Awake</strong> is characterized by its blend of punk rock, funk, and post-punk influences, creating a dynamic and engaging listening experience. Tracks like &quot;Wide Awake&quot; and &quot;Before the Water Gets Too High&quot; highlight the band&apos;s ability to combine sharp, satirical commentary with infectious rhythms and catchy melodies.</p>
  <p>The production of <strong>Wide Awake</strong> is notable for its energetic and raw sound, with a focus on tight grooves and vibrant instrumentation. The album features a mix of driving guitar riffs, syncopated drum patterns, and prominent bass lines, all of which contribute to its energetic and urgent feel. The lyrics often address themes of contemporary life and political issues, delivered with the band&apos;s signature blend of humor and insight. The album&apos;s production captures the band&apos;s live energy and spontaneity, making it a standout entry in their discography.</p>
  <p>Upon its release, <strong>Wide Awake</strong> received critical acclaim for its inventive approach to indie rock and its incisive lyrical content. The album was praised for its ability to blend various musical influences while maintaining a cohesive and engaging sound. <strong>Wide Awake</strong> has been recognized as a significant contribution to Parquet Courts&apos; body of work, further solidifying their reputation as a band capable of combining thought-provoking lyrics with dynamic and compelling music.</p>`
        }          
]
},{
  id:"3",
  type:'ambient',
  min:0,
  max:10,
  list:[{no:1,artist:'Brian Eno',album_name:'Music for Airports',year:1978,genre:'Ambient',length:'1 hrs',tracks:4,link:'https://open.spotify.com/album/063f8Ej8rLVTz9KkjQKEMa?si=db9bc6b8b9b945b0',review:`<p><strong>Music for Airports</strong> is the first album in Brian Eno's pioneering Ambient series, released in 1978. This groundbreaking work is considered one of the first albums to define the ambient genre, focusing on creating a soothing and contemplative atmosphere rather than traditional melodies and rhythms.</p>
    <p>The album consists of four tracks, each designed to be looped and layered, creating a continuous, calming soundscape. Eno's use of minimalism, soft piano notes, and subtle synthesizer tones in pieces like "1/1" and "2/1" contributes to the serene and meditative quality of the music.</p>
    <p><em>Music for Airports</em> was conceived to transform the typically stressful airport environment into a more peaceful and introspective space. It has since become a landmark in ambient music, influencing countless artists and redefining the possibilities of sound in modern music.</p>`
},

{no:4,artist:'Biosphere',album_name:'Substrata',year:1997,genre:'Ambient',length:'1 hrs',tracks:10,link:'https://open.spotify.com/album/5QIf4hNIAksV1uMCXHVkAZ?si=1158e2a896174164',review:`<p><strong>Substrata</strong> is the third studio album by Norwegian electronic musician Biosphere (Geir Jenssen), released in 1997. The album is widely regarded as one of the finest examples of ambient music, known for its cold, atmospheric soundscapes that evoke the stark beauty of Arctic landscapes.</p>
    <p>Tracks like "Kobresia" and "Poa Alpina" blend environmental field recordings with subtle melodies and minimalist arrangements, creating a deeply immersive listening experience. The album's use of natural sounds, such as flowing water and distant echoes, enhances its organic and expansive feel.</p>
    <p><em>Substrata</em> has been praised for its emotional depth and its ability to transport listeners to serene, isolated environments. It remains a seminal work in the ambient genre, influencing a generation of artists with its masterful use of space and texture.</p>`
},

{no:8,artist:'Tim Hecker',album_name:'Harmony In Ultraviolet',year:2006,genre:'Ambient',length:'50 mins',tracks:15,link:'https://open.spotify.com/album/1U5x6wQtMJtbwM3NZRSvKT?si=a3fa34dda4d64bb5',review:`<p><strong>Harmony in Ultraviolet</strong> is the fourth studio album by Canadian electronic musician Tim Hecker, released in 2006. The album is known for its dense, layered soundscapes that blend noise, ambient, and drone music, creating a deeply textured and immersive auditory experience.</p>
    <p>Tracks like "Chimeras" and "Spring Heeled Jack Flies Tonight" showcase Hecker's ability to craft complex sonic environments, where distorted tones and shimmering harmonies coexist. The album's abstract and evolving compositions offer a meditative and sometimes unsettling journey through sound.</p>
    <p><em>Harmony in Ultraviolet</em> is often hailed as one of Hecker's most accomplished works, praised for its innovative approach to sound design and its emotional resonance. The album has solidified Hecker's reputation as a leading figure in the experimental and ambient music scenes.</p>`
},

{no:6,artist:'Steve Roach',album_name:'Structures From Silence',year:1984,genre:'Space Ambient',length:'58 mins',tracks:3,link:'https://open.spotify.com/album/46AY6JPcDEFWYF8YcYOQWh?si=zZsXwPLCRA6WZI6DpFbc2g',review:`<p><strong>Structures from Silence</strong> is the third studio album by American ambient musician Steve Roach, released in 1984. The album is considered a classic in the ambient genre, known for its serene and meditative soundscapes that have been influential in the development of ambient and new age music.</p>
    <p>The title track, "Structures from Silence," is a 30-minute piece that features slowly evolving synth textures and gentle, hypnotic melodies. The album's minimalist approach and its focus on creating a peaceful, reflective atmosphere have made it a favorite among listeners seeking relaxation and introspection.</p>
    <p><em>Structures from Silence</em> is often praised for its timeless quality and its ability to create a sense of stillness and calm. It remains one of Steve Roach's most celebrated works and a cornerstone of ambient music.</p> `
},

{no:9,artist:'Tangerine Dream',album_name:'Phaedra',year:1974,genre:'Ambient',length:'37 mins',tracks:4,link:'https://open.spotify.com/album/6wugThEUTAa6BdI2hsqm5n?si=daf20d9a55844c9f',review:`<p><strong>Phaedra</strong> is the fifth studio album by the German electronic music group Tangerine Dream, released in 1974. The album is a landmark in the development of electronic music, known for its pioneering use of synthesizers and its exploration of cosmic and otherworldly themes.</p>
    <p>Featuring the epic title track "Phaedra," the album blends sequenced synthesizer patterns, ambient textures, and experimental sound design to create a deeply atmospheric and immersive experience. The album's use of Moog synthesizers and Mellotrons was groundbreaking at the time and has influenced countless electronic musicians.</p>
    <p><em>Phaedra</em> was a commercial and critical success, establishing Tangerine Dream as a major force in the world of electronic music. It remains one of their most iconic albums and a seminal work in the space music and ambient genres.</p>`
},

{no:2,artist:'Stars of the Lid',album_name:'And Their Refinement of the Decline',year:2007,genre:'Drone',length:'2 hrs',tracks:18,link:'https://open.spotify.com/album/6cHPEbPryLpH5VX5Eb1Vvo?si=4a737b5acbb54419',review:`<p><strong>Stars of the Lid and Their Refinement of the Decline</strong> is the seventh studio album by the American ambient music duo Stars of the Lid, released in 2007. The album is a double-disc set that is considered one of the duo's most accomplished works, known for its slow, expansive compositions that blend drone, classical, and ambient elements.</p>
    <p>Tracks like "Dopamine Clouds Over Craven Cottage" and "December Hunting for Vegetarian Fuckface" feature lush orchestral arrangements, minimalistic drones, and delicate soundscapes that unfold gradually over long durations. The album's use of strings, horns, and processed sounds creates a deeply immersive and contemplative atmosphere.</p>
    <p><em>Stars of the Lid and Their Refinement of the Decline</em> is often hailed as a masterpiece of ambient music, praised for its emotional depth and its ability to evoke a sense of timelessness and tranquility. It remains a defining album in the ambient genre and a favorite among fans of deeply meditative music.</p>`
},

{no:3,artist:'Grouper',album_name:'Alien Observer',year:2011,genre:'Ambient',length:'40 mins',tracks:6,link:'https://open.spotify.com/album/4Z1BFX1oBckY8bhGEWMYmi?si=sYbHQjOoRNikJ8sfTvi4og',review:`<p><strong>Alien Observer</strong> is one of two albums released in 2011 as part of Grouper's double album project A I A. Created by musician Liz Harris, Grouper's sound on this album is characterized by ethereal, ambient compositions that evoke a sense of isolation and introspection.</p>
    <p>The album features haunting tracks like "Moon is Sharp" and "Alien Observer," which blend Harris's whispery vocals with minimalistic instrumentation and atmospheric drones. The music on <em>Alien Observer</em> is both intimate and otherworldly, creating a deeply immersive listening experience.</p>
    <p><em>Alien Observer</em> has been praised for its emotional depth and has solidified Grouper's reputation as a key figure in the ambient and experimental music scenes. The album continues to resonate with listeners who appreciate its haunting beauty and meditative qualities.</p>`
},
{no:5,artist:'GAS',album_name:'Pop',year:2000,genre:'Ambient',length:'1 hrs 7 mins',tracks:7,link:'https://open.spotify.com/album/32Nl49izVyngH22kD1lrkk?si=vAwKJw-cQfeZdmePxmDwGQ',review:`<p><strong>Pop</strong> is the fourth studio album by German electronic music project GAS, led by Wolfgang Voigt, released in 2000. The album is considered a masterpiece of ambient techno, known for its lush, hypnotic soundscapes that blend classical music samples with subtle, pulsating beats.</p>
    <p>Tracks like "Pop 1" and "Pop 4" feature looping orchestral fragments, layered with deep bass and soft rhythms, creating an immersive, dream-like experience. The album's seamless flow and richly textured sound evoke a sense of being enveloped in a dense forest, reflecting Voigt's connection to the natural world and his unique approach to electronic music.</p>
    <p><em>Pop</em> has been widely acclaimed for its innovative fusion of ambient and techno, and it remains one of the most influential albums in the genre. Its ability to transport listeners to a different realm through its subtle and intricate compositions has made it a timeless classic.</p>`
},

{no:7,artist:'William Basinski',album_name:'The Disintegration Loops',year:2002,genre:'Ambient',length:'5 hrs',tracks:4,link:'https://open.spotify.com/album/5fmPy3XmYD0BJKEr86a3Cu?si=11283db3042f4cfe',review:`<p><strong>The Disintegration Tapes</strong> is a notable work by American composer William Basinski, released in 2002. The album is a collection of tape loops that have decayed over time, creating a unique, poignant exploration of the themes of memory, time, and loss. It is part of Basinski's acclaimed *Disintegration Loops* series.</p>
    <p>The work is characterized by its hauntingly beautiful soundscapes, where the gradual deterioration of magnetic tape creates a mesmerizing, ambient experience. The loops, initially recorded in the 1980s, were rediscovered and played back in their disintegrated state, resulting in an ethereal and reflective sonic journey. The tracks evoke a sense of nostalgia and decay, reflecting on the transient nature of time and memory.</p>
    <p><em>The Disintegration Tapes</em> has been praised for its innovative use of tape decay and its ability to evoke deep emotional responses. It stands as a significant contribution to the ambient and experimental music genres, highlighting Basinski's ability to transform physical decay into a profound auditory experience.</p>`
},

{no:10,artist:'Fripp & Eno',album_name:'Evening Star',year:1975,genre:'Ambient',length:'45 mins',tracks:5,link:'https://open.spotify.com/album/1nVnbkq96iZzBMp57Xzx1V?si=94871fd844744269',review:`<p><strong>Evening Star</strong> is a collaborative album by guitarist Robert Fripp and ambient pioneer Brian Eno, released in 1975. This album is known for its fusion of Fripp's intricate guitar work with Eno's ambient soundscapes, creating a unique and innovative approach to ambient and experimental music.</p>
    <p>The album features a series of instrumental tracks that explore the interplay between Fripp's electric guitar and Eno's ambient textures. Tracks like "Evening Star" and "Wind on Water" showcase their use of Fripp's distinctive "Frippertronics" guitar loops combined with Eno's atmospheric effects, resulting in a mesmerizing and meditative sound.</p>
    <p><em>Evening Star</em> is praised for its pioneering approach to ambient music, combining intricate guitar work with lush, evolving soundscapes. The album stands as a significant contribution to both artists' discographies and remains a classic example of ambient and experimental music from the 1970s.</p>`
},
]
}];

export function randomNumber(min, max) {
  return Math.floor(Math.random() * (max - min) + min);
}



export function renderAlbum(){
    let option = JSON.parse(localStorage.getItem('option'));
    const max = option.max;
    const min = option.min;
    const list = option.list;
    const v = localStorage.getItem('v');
    const overview = document.querySelector('.overview');
    overview.innerHTML = list[v].review;
    document.querySelectorAll('.js-album-link').forEach(function(anchor) {
      anchor.href = list[v].link;
    });
    console.log(localStorage.getItem('v'));
      let intervalId;
      function autoPlay(){
          intervalId = setInterval(function(){
            pickAlbum(list,randomNumber(min,max));}
            ,10);
        }

      

      autoPlay();
      setTimeout(()=>{
        clearInterval(intervalId);
        pickAlbum(list,v);
      },1000);
      

   
      
      
      function pickAlbum(list,v){
      const album_img = document.getElementById("artwork");
      const album_nme = document.getElementById("title");
      const album_artist = document.getElementById("artist");
      const album_infoss = document.getElementById("oinfo");
      const album_nos = document.getElementById("no");
      album_img.src = `albums/${list[v].album_name}.jpg`;
      album_nme.innerText = list[v].album_name;
      album_artist.innerText = list[v].artist;
      album_infoss.innerText = `${list[v].year} ‧ ${list[v].genre} ‧ ${list[v].tracks} songs ‧ ${list[v].length}`
      album_nos.innerHTML = `${list[v].no}.`;
      
      setTimeout(()=>{
        document.querySelector('.overview').classList.add('after');
        document.querySelector('.links-container').classList.add('after');
      },1100);
      
      }

    }